[package]
authors = ['Logion Team <https://github.com/logion-network>']
build = 'build.rs'
description = 'A Logion network node.'
edition = '2018'
homepage = 'https://logion.network'
license = 'Apache 2.0'
name = 'logion-node'
repository = 'https://github.com/logion-network/logion-node'
version = '3.0.0'

[[bin]]
name = 'logion-node'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = '3.0.0'

[dependencies]
jsonrpc-core = '15.1.0'
structopt = '0.3.8'
bs58 = '0.4.0'
serde_json = '1.0.59'

# Substrate dependencies
environmental = '1.1.3'
frame-benchmarking = '3.1.0'
frame-benchmarking-cli = '3.0.0'
pallet-transaction-payment-rpc = '3.0.0'
sc-basic-authorship = '0.9.0'
sc-cli = { features = ['wasmtime'], version = '0.9.0' }
sc-client-api = '3.0.0'
sc-consensus = '0.9.0'
sc-consensus-aura = '0.9.0'
sc-executor = { features = ['wasmtime'], version = '0.9.0' }
sc-finality-grandpa = '0.9.0'
sc-keystore = '3.0.0'
sc-rpc = '3.0.0'
sc-rpc-api = '0.9.0'
sc-service = { features = ['wasmtime'], version = '0.9.0' }
sc-telemetry = '3.0.0'
sc-transaction-pool = '3.0.0'
sp-api = '3.0.0'
sp-block-builder = '3.0.0'
sp-blockchain = '3.0.0'
sp-consensus = '0.9.0'
sp-consensus-aura = '0.9.0'
sp-core = '3.0.0'
sp-finality-grandpa = '3.0.0'
sp-inherents = '3.0.0'
sp-runtime = '3.0.0'
sp-transaction-pool = '3.0.0'
substrate-frame-rpc-system = '3.0.0'
parity-db = "0.3.4"

# local dependencies
logion-node-runtime = { path = '../runtime', version = '3.0.0' }

[features]
default = []
runtime-benchmarks = ['logion-node-runtime/runtime-benchmarks']
