
//! Autogenerated weights for `pallet_logion_vote`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-12-06, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `gerard-XPS-13-9305`, CPU: `11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/logion-node
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --pallet
// pallet_logion_vote
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// runtime/src/weights/pallet_logion_vote.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_logion_vote`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_logion_vote::WeightInfo for WeightInfo<T> {
	/// Storage: `LoAuthorityList::LegalOfficerSet` (r:3 w:0)
	/// Proof: `LoAuthorityList::LegalOfficerSet` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LogionLoc::LocMap` (r:1 w:0)
	/// Proof: `LogionLoc::LocMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Vote::LastVoteId` (r:1 w:1)
	/// Proof: `Vote::LastVoteId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Vote::Votes` (r:0 w:1)
	/// Proof: `Vote::Votes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_vote_for_all_legal_officers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `537`
		//  Estimated: `8952`
		// Minimum execution time: 27_258_000 picoseconds.
		Weight::from_parts(27_766_000, 0)
			.saturating_add(Weight::from_parts(0, 8952))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Vote::Votes` (r:1 w:1)
	/// Proof: `Vote::Votes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `166`
		//  Estimated: `3631`
		// Minimum execution time: 16_964_000 picoseconds.
		Weight::from_parts(17_635_000, 0)
			.saturating_add(Weight::from_parts(0, 3631))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
