
//! Autogenerated weights for `pallet_lo_authority_list`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-02-29, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `gerard-XPS-13-9305`, CPU: `11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/logion-node
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --pallet
// pallet_lo_authority_list
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// runtime/src/weights/pallet_lo_authority_list.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_lo_authority_list`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_lo_authority_list::WeightInfo for WeightInfo<T> {
	/// Storage: `LoAuthorityList::LegalOfficerSet` (r:101 w:1)
	/// Proof: `LoAuthorityList::LegalOfficerSet` (`max_values`: None, `max_size`: Some(2185), added: 4660, mode: `MaxEncodedLen`)
	/// Storage: `LoAuthorityList::LegalOfficerNodes` (r:0 w:1)
	/// Proof: `LoAuthorityList::LegalOfficerNodes` (`max_values`: Some(1), `max_size`: Some(13002), added: 13497, mode: `MaxEncodedLen`)
	fn add_legal_officer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9309`
		//  Estimated: `471650`
		// Minimum execution time: 418_485_000 picoseconds.
		Weight::from_parts(426_943_000, 0)
			.saturating_add(Weight::from_parts(0, 471650))
			.saturating_add(T::DbWeight::get().reads(101))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `LoAuthorityList::LegalOfficerSet` (r:101 w:1)
	/// Proof: `LoAuthorityList::LegalOfficerSet` (`max_values`: None, `max_size`: Some(2185), added: 4660, mode: `MaxEncodedLen`)
	/// Storage: `LoAuthorityList::LegalOfficerNodes` (r:0 w:1)
	/// Proof: `LoAuthorityList::LegalOfficerNodes` (`max_values`: Some(1), `max_size`: Some(13002), added: 13497, mode: `MaxEncodedLen`)
	fn remove_legal_officer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9400`
		//  Estimated: `471650`
		// Minimum execution time: 598_565_000 picoseconds.
		Weight::from_parts(621_236_000, 0)
			.saturating_add(Weight::from_parts(0, 471650))
			.saturating_add(T::DbWeight::get().reads(101))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `LoAuthorityList::LegalOfficerSet` (r:101 w:1)
	/// Proof: `LoAuthorityList::LegalOfficerSet` (`max_values`: None, `max_size`: Some(2185), added: 4660, mode: `MaxEncodedLen`)
	/// Storage: `LoAuthorityList::LegalOfficerNodes` (r:0 w:1)
	/// Proof: `LoAuthorityList::LegalOfficerNodes` (`max_values`: Some(1), `max_size`: Some(13002), added: 13497, mode: `MaxEncodedLen`)
	fn update_legal_officer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9400`
		//  Estimated: `471650`
		// Minimum execution time: 410_435_000 picoseconds.
		Weight::from_parts(427_006_000, 0)
			.saturating_add(Weight::from_parts(0, 471650))
			.saturating_add(T::DbWeight::get().reads(101))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `LoAuthorityList::LegalOfficerSet` (r:101 w:1)
	/// Proof: `LoAuthorityList::LegalOfficerSet` (`max_values`: None, `max_size`: Some(2185), added: 4660, mode: `MaxEncodedLen`)
	/// Storage: `LoAuthorityList::LegalOfficerNodes` (r:0 w:1)
	/// Proof: `LoAuthorityList::LegalOfficerNodes` (`max_values`: Some(1), `max_size`: Some(13002), added: 13497, mode: `MaxEncodedLen`)
	fn import_host_legal_officer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9309`
		//  Estimated: `471650`
		// Minimum execution time: 406_380_000 picoseconds.
		Weight::from_parts(432_396_000, 0)
			.saturating_add(Weight::from_parts(0, 471650))
			.saturating_add(T::DbWeight::get().reads(101))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `LoAuthorityList::LegalOfficerSet` (r:2 w:1)
	/// Proof: `LoAuthorityList::LegalOfficerSet` (`max_values`: None, `max_size`: Some(2185), added: 4660, mode: `MaxEncodedLen`)
	fn import_guest_legal_officer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `878`
		//  Estimated: `10310`
		// Minimum execution time: 23_398_000 picoseconds.
		Weight::from_parts(27_347_000, 0)
			.saturating_add(Weight::from_parts(0, 10310))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
