name: Build Node

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install required packages
        uses: ConorMacBride/install-package@v1.1.0
        with:
          apt: protobuf-compiler
      - uses: actions/checkout@v3
      - name: Check Cargo version
        run: cargo --version --verbose
      - name: Check Rust Toolchain
        run: rustup show --verbose
      - name: Build
        run: cargo build --verbose --locked
