name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check Cargo version
        run: cargo --version --verbose
      - name: Update Rust
        run: rustup update ; rustup update nightly ; rustup target add wasm32-unknown-unknown --toolchain nightly
      - name: Check Rust version
        run: rustup show
      - name: Build
        run: cargo build --verbose
